### ISSUE TITLE
Feature Request: Add support for MDX Files

### ISSUE THREAD

**Issue by blowsie** [etchteam/storybook-addon-status#11]
I tried to apply a status in an mdx file with the following syntax.
```
<Meta title="Style Guide/Colors" parameters="{{ status: 'stable' }}"/>
```

This didn't work, is the add-on missing support for it?

**Comment by blowsie** [comment]
My bad...

This works.
```<Meta title="Style Guide/Colors" parameters={{ status: 'stable' }} />```

**Comment by gavmck** [comment]
Phew! Good spot
