### ISSUE TITLE
Missing console.log

### ISSUE THREAD

**Issue by HosseinAgha** [etchteam/storybook-addon-status#14]
I think you've missed a console.log in your codebase. https://github.com/etchteam/storybook-addon-status/blob/9d3573b8250b0ea3f4ad6fc73327c3726c963748/src/register.tsx#L20

**Comment by gavmck** [comment]
Woops, thanks! Fixed on 3.0.1 out now

**Comment by HosseinAgha** [comment]
You can use eslint to throw errors for these missed `console.log`
