### ISSUE TITLE
Can you show how to add options with different colors in the documentation?

### ISSUE THREAD

**Issue by CodeByAlex** [etchteam/storybook-addon-status#2]

**Comment by gavmck** [comment]
Hey Alex,

At the moment you can just pass in `stable|beta|depreciated` which have preset colours.
I'm assuming you want custom labels and colours?

**Comment by CodeByAlex** [comment]
Yeah that’s definitely what I’m looking for and I think, if supported, your addon could really help me out. Any chance that’s something you would be interested in adding to increase flexibility?

**Comment by gavmck** [comment]
Sure that sounds sensible, I guess pass in an array of labels and associated colours. 

I'm pretty slammed this week, but might be able to get it out next week or you can open a PR :)

**Comment by gavmck** [comment]
Now available on [v2.0.0](https://www.npmjs.com/package/@etchteam/storybook-addon-status)

Added an [explanation](https://github.com/etchteam/storybook-addon-status#custom-statuses) to the docs

**Comment by CodeByAlex** [comment]
Thanks @gavmck🙏
