### ISSUE TITLE
Feature Request: Allow multiple status badges

### ISSUE THREAD

**Issue by stefan-schweiger** [etchteam/storybook-addon-status#21]
It would be awesome if `type: string` would be extended to `type: string | string[]` and then multiple badges would be displayed.

As far as the sidebar indicator go, I think either showing only the first one or not trying to limit them would both be fine.

**Comment by Tim-arts** [comment]
This feature would be a nice addition!

**Comment by gavmck** [comment]
What's the use case on this? 
Feels like this would conflict with the default statuses.

**Comment by stefan-schweiger** [comment]
@gavmck my personal use case for badges is more to handle them like tags are used by github projects and convey information about a collection of possible status categories.

For example two stories could have the following badges

- `WIP`, `FREE` 
- `STABLE`, `DOCUMENTATION INCOMPLETE`, `PAID`

**Comment by eltranseunteurbano** [comment]
This It's something that I am looking for a while. In my case, I use status as badges to categorized different components.

**Comment by mryechkin** [comment]
Agreed with others, would love to see this feature. Was having some issues with the `badges` addon, so decided to give this one a try instead. Everything works great, but this feature is pretty important for our use case (similar to @stefan-schweiger above)

**Comment by gavmck** [comment]
PRs welcome!

**Comment by Tim-arts** [comment]
If anyone consider making a PR, you could look about this thread to get some inspiration about it: https://github.com/geometricpanda/geometricpanda/issues/20

**Comment by stefan-schweiger** [comment]
@gavmck I could give it a try, but I don't have any experience developing storybook extensions. Any advice how to get started and get this project running in an dev environment?

**Comment by gavmck** [comment]
I think I made a basic storybook setup then I use `npm link` to link to the local repo version for this package whilst developing.

**Comment by stefan-schweiger** [comment]
@gavmck thanks that worked pretty well, I've created a PR. Have a look if you like the type definitions and the handling. It shouldn't break old configs which is important. Probably the docs should also be updated if this gets merged.

**Comment by gavmck** [comment]
Out on 4.1.0! https://www.npmjs.com/package/@etchteam/storybook-addon-status
