### ISSUE TITLE
react shouldn't be a dependency

### ISSUE THREAD

**Issue by criography** [etchteam/storybook-addon-status#30]
Hi,

First of all thank you for creating and managing this addon - it's really helpful:) 

We seem to be having an issue with it requiring `react@16.x` which clashes with latest `17` or `18` and causes a fatal error as described here: https://github.com/storybookjs/storybook/issues/13670#issuecomment-1048259752

While you may require React to be present it your `node_modules`, surely you should not ship it as part of this library/package? So perhaps it should be a `devDependency` and `peerDependency` instead?

What do you think?

**Comment by gavmck** [comment]
Yeah, it should be a devDep or peerDep, you're right!
Fancy making a PR?

**Comment by criography** [comment]
On it.

**Comment by criography** [comment]
bumped dev dependency to 17.x, since it's stable and non-breaking but peer allows for both. Even though 18 was recently released, it feels a bit too fresh too me, and I didn't want to make that call for you, so didn't include it.

**Comment by loucostello** [comment]
It looks like https://github.com/etchteam/storybook-addon-status/pull/45 moved React back to dependencies and pins it on 18, undoing the work here? My project uses React 17 and so I had to add the `resolutions` property to my package.json for this addon to stop throwing an error on the Storybook 7 Docs pages.
