### ISSUE TITLE
Storybook 6.5.0 beta compat

### ISSUE THREAD

**Issue by blowsie** [etchteam/storybook-addon-status#33]
Is this working with Storybook 6.5.0?  I upgraded my storybook to this version and the plugin is no longer working.

I also noticed the package json file references a non-existent file.
```
  "main": "dist/index.js",
  ```

**Comment by gavmck** [comment]
Saying that, I realised we have a storybook on `6.5.0-beta.1` and it seems to be working fine.

**Comment by blowsie** [comment]
Perhaps is something to do with using vue and missing a react dependency or something I will investigate and reopen with a repro or some useful info. Thanks
