### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by AntonyFagundez** [etchteam/storybook-addon-status#35]
Hi thanks for the amazing library, 

For use with React 18 we have problems with deps (npm run ci), I can see the peer deps and have React 16 and 17, but not 18.

https://github.com/etchteam/storybook-addon-status/blob/c555580f54c52ecabdcb16180416c249ea271ab6/package.json#L49

Adding can be add support to react 18: 

```json
 "react": "^16.8.3 || ^17.0.2 || ^18.0.0" 
```

If that's the case, I'd be happy to help.

Regards!

**Comment by jclarkcisco** [comment]
@AntonyFagundez I created the PR here > https://github.com/etchteam/storybook-addon-status/pull/36 hopefully this moves this along. Sorry for taking that away from you. :D

**Comment by AntonyFagundez** [comment]
hahah not problem! Thanks for PR. Expect that approved quickly.

**Comment by jclarkcisco** [comment]
@gavmck - please review #36 when you get a moment.

**Comment by gavmck** [comment]
Out on 4.2.2, sorry for late merge!
