### ISSUE TITLE
Display status in addon-docs tab

### ISSUE THREAD

**Issue by martpie** [etchteam/storybook-addon-status#5]
Hello there! 

Thanks for the great add-on! 

Would it be possible to display the status badge on the addon-docs tab as well? (I am using Storybook v6 btw)

<img width="1037" alt="Screen Shot 2020-10-22 at 17 21 32" src="https://user-images.githubusercontent.com/1311607/96893635-34932400-148b-11eb-9a7e-2bf1229d8bf1.png">

<img width="1162" alt="Screen Shot 2020-10-22 at 17 21 28" src="https://user-images.githubusercontent.com/1311607/96893633-33fa8d80-148b-11eb-8ebc-f5724629e7df.png">

**Comment by gavmck** [comment]
Flattery will get you everywhere 😄 

I think we just need to update this line: https://github.com/etchteam/storybook-addon-status/blob/master/src/register.tsx#L62

I'll check it out next week, or PRs are welcome!

**Comment by gavmck** [comment]
Released on 2.1.0!
