### ISSUE TITLE
React 18.13.x compatibility

### ISSUE THREAD

**Issue by jbojcic1** [etchteam/storybook-addon-status#62]
Currently the package json lists react-dom as dependency with ^18.12.0 while react is pinned to 18.12.0. Why is this so?

In my project I am using react and react-dom 18.13.1 and this causes the plugin to use react 18.12.0 and react-dom 18.13.1 so I am getting this warning:

```
└─┬ @etchteam/storybook-addon-status 4.2.4
  └─┬ react-dom 18.3.1
    └── ✕ unmet peer react@^18.3.1: found 18.2.0 in @etchteam/storybook-addon-status
```

**Comment by JoshTheWanderer** [comment]
Hey @jbojcic1 we've fixed this in [v5](https://www.npmjs.com/package/@etchteam/storybook-addon-status/v/5.0.0), thanks for the report!
